# TODO(leomichalski): apos separar sidekiq, ver se esta funcionando
version: "3"

volumes:
  local-redis-queue-data: {}
  local-redis-cache-data: {}
  local-postgres-data: {}
  local-certbot-www: {}
  local-certbot-conf: {}

services:
  # TODO(leomichalski): sidekiq service
  postgres:
    image: postgres:14.10-alpine
    container_name: local-db
    ports:
      - 5432:5432
    networks:
      - local-app-network
    volumes:
      - local-postgres-data:/var/lib/postgresql/data:rw
    env_file:
      - .envs/local/database

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: local-app
    container_name: local-app
    depends_on:
      - postgres
      - redis-queue
      - redis-cache
    ports:
      - 3035:3035
      - 3000:3000
      - 1080:1080
      - 1025:1025
    networks:
      - local-app-network
    environment:
      - RAILS_ENV=development
      - RACK_ENV=development
      - NODE_ENV=development
    env_file:
      - .envs/local/database
      - .envs/local/admin
      - .envs/local/admin_password
      - .envs/local/redis_queue  # uri
      - .envs/local/redis_cache  # uri
      - .envs/local/decidim_service
      - .envs/local/hostname

  redis-queue:
    image: redis:6.0-alpine
    container_name: local-redis-queue
    command: sh -c "redis-server --port $${REDIS_PORT}"
    ports:
      - 6379:6379
    networks:
      - local-app-network
    volumes:
      - local-redis-queue-data:/data:rw
    env_file:
      - .envs/local/redis_queue  # defines REDIS_PORT

  redis-cache:
    image: redis:6.0-alpine
    container_name: local-redis-cache
    command: sh -c "redis-server --port $${REDIS_CACHE_PORT}"
    ports:
      - 6380:6380
    networks:
      - local-app-network
    volumes:
      - local-redis-cache-data:/data:rw
    env_file:
      - .envs/local/redis_cache  # defines REDIS_CACHE_PORT

networks:
  local-app-network:
    driver: bridge
