development:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { ENV.fetch('REDIS_URL') } %>

test:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { ENV.fetch('REDIS_URL') } %>

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { ENV.fetch('REDIS_URL') } %>